# Generated by Django 4.1.7 on 2023-02-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagensAleatorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariomensagemaleatoria',
            old_name='dataUltimoAcesso',
            new_name='dataPrimeiroAcesso',
        ),
    ]
