# Generated by Django 4.1.7 on 2023-02-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='descricao',
            field=models.TextField(default='Digite sua mensagem', verbose_name='Descrição'),
        ),
    ]
