# Generated by Django 4.1.7 on 2023-02-16 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_alter_mensagens_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagens',
            options={'verbose_name_plural': 'Mensagen'},
        ),
    ]
