# Generated by Django 4.1.7 on 2023-02-17 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensagens', '0003_alter_mensagens_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagens',
            options={},
        ),
        migrations.AddField(
            model_name='mensagens',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
